// flow-typed signature: 279b04443d23463924ccc7fe0a5818f7
// flow-typed version: <<STUB>>/jest_v^18.0.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest/bin/jest' {
  declare module.exports: any;
}

declare module 'jest/build/jest' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest/bin/jest.js' {
  declare module.exports: $Exports<'jest/bin/jest'>;
}
declare module 'jest/build/jest.js' {
  declare module.exports: $Exports<'jest/build/jest'>;
}
